### PR TITLE
Category undefined issue fixed for WP-4.9 & added support for Yoast SEO Breadcumb 

### LINKED ISSUE #13: Add support for Yoast SEO breadcrumb for category page.

### LINKED ISSUE #16: Category undefined issue fixed for WP-4.9

### LINKED ISSUE #17: Update version number & changelog

### LINKED ISSUE #18: Check if SEO Bradcrumb shortcode does exist before printing?

### PR DESCRIPTION
**Pull request by aniljadhavmca**
Fix #13 
Fix #16 
Fix #17 
Fix #18

### CODE REVIEW

File: includes/taxonomy-bsf-docs-cat.php [hunk 1]
```diff
@@ -24,7 +24,7 @@
 		<div class="bsf-page-header">
 			<?php
 				echo '<h1 class="page-title">' . single_cat_title( '', false ) . '</h1>';
-				the_archive_description( '<div class="taxonomy-description">', '</div>' );
+				echo '<div class="tax-breadcrumb">' . do_shortcode( '[wpseo_breadcrumb]' ) . '</div>';
```
Comment (Nikschavan) [inline includes/taxonomy-bsf-docs-cat.php]: What if I don't have `wordpress-seo` installed and I don't want to install it?

Comment (aniljadhavmca) [reply includes/taxonomy-bsf-docs-cat.php]: No issue if you do not have `wordpress-seo` Installed, We have just added support to the `wordpress-seo`  breadcrumb.

Comment (Nikschavan) [reply includes/taxonomy-bsf-docs-cat.php]: What I am saying is what will it print on the screen when the shortcode does not exist? This is how it will look like - https://cl.ly/no9Y
You should check if that shortcode does exist before printing it on the screen.

Comment (Nikschavan) [reply includes/taxonomy-bsf-docs-cat.php]: Also, add a prefix of `bsf` when adding HTML classes so there is no conflict when any CSS is added for this.
